# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto.auth import auth_pb2 as proto_dot_auth_dot_auth__pb2
from proto.iam import users_pb2 as proto_dot_iam_dot_users__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/auth/auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserToken = channel.unary_unary(
                '/auth.Auth/GetUserToken',
                request_serializer=proto_dot_iam_dot_users__pb2.UserLoginPassword.SerializeToString,
                response_deserializer=proto_dot_auth_dot_auth__pb2.UserToken.FromString,
                _registered_method=True)
        self.RefreshUserToken = channel.unary_unary(
                '/auth.Auth/RefreshUserToken',
                request_serializer=proto_dot_auth_dot_auth__pb2.RefreshToken.SerializeToString,
                response_deserializer=proto_dot_auth_dot_auth__pb2.UserToken.FromString,
                _registered_method=True)
        self.DeleteUserToken = channel.unary_unary(
                '/auth.Auth/DeleteUserToken',
                request_serializer=proto_dot_auth_dot_auth__pb2.RefreshToken.SerializeToString,
                response_deserializer=proto_dot_auth_dot_auth__pb2.UserToken.FromString,
                _registered_method=True)
        self.CheckUserToken = channel.unary_unary(
                '/auth.Auth/CheckUserToken',
                request_serializer=proto_dot_auth_dot_auth__pb2.UserToken.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CheckBotToken = channel.unary_unary(
                '/auth.Auth/CheckBotToken',
                request_serializer=proto_dot_auth_dot_auth__pb2.BotToken.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class AuthServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUserToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshUserToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUserToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckUserToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckBotToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserToken,
                    request_deserializer=proto_dot_iam_dot_users__pb2.UserLoginPassword.FromString,
                    response_serializer=proto_dot_auth_dot_auth__pb2.UserToken.SerializeToString,
            ),
            'RefreshUserToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshUserToken,
                    request_deserializer=proto_dot_auth_dot_auth__pb2.RefreshToken.FromString,
                    response_serializer=proto_dot_auth_dot_auth__pb2.UserToken.SerializeToString,
            ),
            'DeleteUserToken': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUserToken,
                    request_deserializer=proto_dot_auth_dot_auth__pb2.RefreshToken.FromString,
                    response_serializer=proto_dot_auth_dot_auth__pb2.UserToken.SerializeToString,
            ),
            'CheckUserToken': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUserToken,
                    request_deserializer=proto_dot_auth_dot_auth__pb2.UserToken.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CheckBotToken': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckBotToken,
                    request_deserializer=proto_dot_auth_dot_auth__pb2.BotToken.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.Auth', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('auth.Auth', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Auth(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUserToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.Auth/GetUserToken',
            proto_dot_iam_dot_users__pb2.UserLoginPassword.SerializeToString,
            proto_dot_auth_dot_auth__pb2.UserToken.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshUserToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.Auth/RefreshUserToken',
            proto_dot_auth_dot_auth__pb2.RefreshToken.SerializeToString,
            proto_dot_auth_dot_auth__pb2.UserToken.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUserToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.Auth/DeleteUserToken',
            proto_dot_auth_dot_auth__pb2.RefreshToken.SerializeToString,
            proto_dot_auth_dot_auth__pb2.UserToken.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckUserToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.Auth/CheckUserToken',
            proto_dot_auth_dot_auth__pb2.UserToken.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckBotToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.Auth/CheckBotToken',
            proto_dot_auth_dot_auth__pb2.BotToken.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
