# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/auth/auth.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'proto/auth/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto.iam import users_pb2 as proto_dot_iam_dot_users__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/auth/auth.proto\x12\x04\x61uth\x1a\x1bgoogle/protobuf/empty.proto\x1a\x15proto/iam/users.proto\"5\n\tUserToken\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\x12\x11\n\tjwt_token\x18\x02 \x01(\t\"%\n\x0cRefreshToken\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\"\'\n\x08\x42otToken\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t2\xb0\x02\n\x04\x41uth\x12;\n\x0cGetUserToken\x12\x18.users.UserLoginPassword\x1a\x0f.auth.UserToken\"\x00\x12\x39\n\x10RefreshUserToken\x12\x12.auth.RefreshToken\x1a\x0f.auth.UserToken\"\x00\x12\x38\n\x0f\x44\x65leteUserToken\x12\x12.auth.RefreshToken\x1a\x0f.auth.UserToken\"\x00\x12;\n\x0e\x43heckUserToken\x12\x0f.auth.UserToken\x1a\x16.google.protobuf.Empty\"\x00\x12\x39\n\rCheckBotToken\x12\x0e.auth.BotToken\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.auth.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERTOKEN']._serialized_start=83
  _globals['_USERTOKEN']._serialized_end=136
  _globals['_REFRESHTOKEN']._serialized_start=138
  _globals['_REFRESHTOKEN']._serialized_end=175
  _globals['_BOTTOKEN']._serialized_start=177
  _globals['_BOTTOKEN']._serialized_end=216
  _globals['_AUTH']._serialized_start=219
  _globals['_AUTH']._serialized_end=523
# @@protoc_insertion_point(module_scope)
