name: Create and publish a Docker image

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      registry:
        required: true
        type: string
      actor:
        required: true
        type: string

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.1

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6.9.0
        with:
          context: "${{defaultContext}}:${{ inputs.service_name }}"
          push: true
          tags: |
            ${{ inputs.service_name }}:${{ github.ref }}
            ${{ inputs.service_name }}:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1.4.3
        with:
          subject-name: ${{ inputs.registry }}/${{ inputs.service_name }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
