name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.2.1
      - name: Create Release
        id: create_release
        uses: comnoco/create-release-action@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  publish-containers:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Publish auth service
        uses: ./.github/actions/container/publish.yml
        with:
          service_name: auth
          registry: ghcr.io
          actor: ${{ github.actor }}
          version: ${{ github.ref }}
