name: Build Stable

on:
  push:
    branches :
      - 'testing'

jobs:
  publish-containers:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
        with:
          ref: ${{ github.ref }}
      - name: Publish auth service
        uses: ./.github/actions/publish-container
        with:
          service_name: auth
          registry: ghcr.io
          actor: ${{ github.actor }}
          version: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}